server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: kindledger-gateway
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  # PostgreSQL Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://kindledger-postgres:5432/kindledger}
    username: ${SPRING_DATASOURCE_USERNAME:kindledger}
    password: ${SPRING_DATASOURCE_PASSWORD:kindledger123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://kindledger-mongodb:27017/kindledger}
      auto-index-creation: true
  
  # Redis Configuration
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:kindledger123}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms

fabric:
  networkConfigPath: ${FABRIC_NETWORKCONFIGPATH:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/connection-profile.yaml}
  channelName: ${FABRIC_CHANNELNAME:kindchannel}
  chaincodeName: ${FABRIC_CHAINCODENAME:kindledgercc}
  organization: ${FABRIC_ORGANIZATION:MBBank}
  user: ${FABRIC_USER:Admin@mb.kindledger.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    db:
      enabled: true
    mongo:
      enabled: true

logging:
  level:
    com.kindledger.gateway: DEBUG
    org.hyperledger.fabric: INFO
    org.springframework.web: DEBUG
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
