spring:
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://kindledger-postgres:5432/kindledger
    username: kindledger
    password: kindledger123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://kindledger:kindledger123@kindledger-mongodb:27017/kindledger?authSource=admin
      auto-index-creation: true

  # Redis Configuration - Using environment variables from docker-compose
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:kindledger123}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms

fabric:
  networkConfigPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/config/connection-profile.yaml
  channelName: kindchannel
  chaincodeName: kindledgercc
  organization: MBBank
  user: Admin@mb.kindledger.com

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
