name: kindledger-network
version: "1.0"
client:
  organization: MBBank
  connection:
    timeout:
      peer:
        endorser: "300"
      orderer: "300"
channels:
  kindchannel:
    orderers:
      - orderer.kindledger.com
    peers:
      peer0.mb.kindledger.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
        discover: true
      peer0.charity.kindledger.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.supplier.kindledger.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.auditor.kindledger.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
organizations:
  MBBank:
    mspid: MBBankMSP
    peers:
      - peer0.mb.kindledger.com
    certificateAuthorities:
      - ca.mb.kindledger.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/mb.kindledger.com/users/Admin@mb.kindledger.com/msp/keystore/priv_sk
    signedCert:
      path: crypto-config/peerOrganizations/mb.kindledger.com/users/Admin@mb.kindledger.com/msp/signcerts/Admin@mb.kindledger.com-cert.pem
  Charity:
    mspid: CharityMSP
    peers:
      - peer0.charity.kindledger.com
    certificateAuthorities:
      - ca.charity.kindledger.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/charity.kindledger.com/users/Admin@charity.kindledger.com/msp/keystore/priv_sk
    signedCert:
      path: crypto-config/peerOrganizations/charity.kindledger.com/users/Admin@charity.kindledger.com/msp/signcerts/Admin@charity.kindledger.com-cert.pem
  Supplier:
    mspid: SupplierMSP
    peers:
      - peer0.supplier.kindledger.com
    certificateAuthorities:
      - ca.supplier.kindledger.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/supplier.kindledger.com/users/Admin@supplier.kindledger.com/msp/keystore/priv_sk
    signedCert:
      path: crypto-config/peerOrganizations/supplier.kindledger.com/users/Admin@supplier.kindledger.com/msp/signcerts/Admin@supplier.kindledger.com-cert.pem
  Auditor:
    mspid: AuditorMSP
    peers:
      - peer0.auditor.kindledger.com
    certificateAuthorities:
      - ca.auditor.kindledger.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/auditor.kindledger.com/users/Admin@auditor.kindledger.com/msp/keystore/priv_sk
    signedCert:
      path: crypto-config/peerOrganizations/auditor.kindledger.com/users/Admin@auditor.kindledger.com/msp/signcerts/Admin@auditor.kindledger.com-cert.pem
orderers:
  orderer.kindledger.com:
    url: grpcs://orderer.orderer.kindledger.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.orderer.kindledger.com
      grpc.keepalive_time_ms: 60000
      grpc.keepalive_timeout_ms: 5000
      grpc.keepalive_permit_without_calls: true
      grpc.http2.max_pings_without_data: 0
      grpc.http2.min_time_between_pings_ms: 10000
      grpc.http2.min_ping_interval_without_data_ms: 300000
    tlsCACerts:
      path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.kindledger.com/orderers/orderer.orderer.kindledger.com/msp/tlscacerts/tlsca.orderer.kindledger.com-cert.pem
peers:
  peer0.mb.kindledger.com:
    url: grpcs://peer0.mb.kindledger.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.mb.kindledger.com
      grpc.keepalive_time_ms: 60000
      grpc.keepalive_timeout_ms: 5000
      grpc.keepalive_permit_without_calls: true
      grpc.http2.max_pings_without_data: 0
      grpc.http2.min_time_between_pings_ms: 10000
      grpc.http2.min_ping_interval_without_data_ms: 300000
    tlsCACerts:
      path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mb.kindledger.com/peers/peer0.mb.kindledger.com/tls/ca.crt
  peer0.charity.kindledger.com:
    url: grpcs://peer0.charity.kindledger.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.charity.kindledger.com
      grpc.keepalive_time_ms: 60000
      grpc.keepalive_timeout_ms: 5000
      grpc.keepalive_permit_without_calls: true
      grpc.http2.max_pings_without_data: 0
      grpc.http2.min_time_between_pings_ms: 10000
      grpc.http2.min_ping_interval_without_data_ms: 300000
    tlsCACerts:
      path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/charity.kindledger.com/peers/peer0.charity.kindledger.com/tls/ca.crt
  peer0.supplier.kindledger.com:
    url: grpcs://peer0.supplier.kindledger.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.supplier.kindledger.com
      grpc.keepalive_time_ms: 60000
      grpc.keepalive_timeout_ms: 5000
      grpc.keepalive_permit_without_calls: true
      grpc.http2.max_pings_without_data: 0
      grpc.http2.min_time_between_pings_ms: 10000
      grpc.http2.min_ping_interval_without_data_ms: 300000
    tlsCACerts:
      path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplier.kindledger.com/peers/peer0.supplier.kindledger.com/tls/ca.crt
  peer0.auditor.kindledger.com:
    url: grpcs://peer0.auditor.kindledger.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.auditor.kindledger.com
      grpc.keepalive_time_ms: 60000
      grpc.keepalive_timeout_ms: 5000
      grpc.keepalive_permit_without_calls: true
      grpc.http2.max_pings_without_data: 0
      grpc.http2.min_time_between_pings_ms: 10000
      grpc.http2.min_ping_interval_without_data_ms: 300000
    tlsCACerts:
      path: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/auditor.kindledger.com/peers/peer0.auditor.kindledger.com/tls/ca.crt
certificateAuthorities:
  ca.mb.kindledger.com:
    url: https://localhost:7054
    caName: ca-mb
    tlsCACerts:
      path: crypto-config/peerOrganizations/mb.kindledger.com/ca/ca.mb.kindledger.com-cert.pem
    httpOptions:
      verify: false
  ca.charity.kindledger.com:
    url: https://localhost:8054
    caName: ca-charity
    tlsCACerts:
      path: crypto-config/peerOrganizations/charity.kindledger.com/ca/ca.charity.kindledger.com-cert.pem
    httpOptions:
      verify: false
  ca.supplier.kindledger.com:
    url: https://localhost:9054
    caName: ca-supplier
    tlsCACerts:
      path: crypto-config/peerOrganizations/supplier.kindledger.com/ca/ca.supplier.kindledger.com-cert.pem
    httpOptions:
      verify: false
  ca.auditor.kindledger.com:
    url: https://localhost:10054
    caName: ca-auditor
    tlsCACerts:
      path: crypto-config/peerOrganizations/auditor.kindledger.com/ca/ca.auditor.kindledger.com-cert.pem
    httpOptions:
      verify: false
