peer:
  id: peer0.mb.kindledger.com
  networkId: dev
  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052
  chaincodeAddress: 0.0.0.0:7052
  address: 0.0.0.0:7051
  addressAutoDetect: true
  gomaxprocs: -1
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    bootstrap: 127.0.0.1:7051
    useLeaderElection: true
    orgLeader: false
    membershipTrackerInterval: 5s
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval:
    publishCertPeriod: 10s
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    externalEndpoint:
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
    pvtData:
      pullRetryThreshold: 60s
      transientstoreMaxBlockRetention: 1000
      pushAckTimeout: 3s
      btlPullMargin: 10
      reconcileBatchSize: 10
      reconcileSleepInterval: 1m
      reconciliationEnabled: true
      skipPullingInvalidTransactionsDuringCommit: false
    state:
      enabled: true
      checkInterval: 10s
      responseTimeout: 3s
      batchSize: 10
      blockBufferSize: 100
      maxRetries: 3
  events:
    address: 0.0.0.0:7053
    buffersize: 100
    timeout: 10ms
    timewindow: 15m
    keepalive:
      minInterval: 60s
    sendTimeout: 60s
  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: /etc/hyperledger/fabric/tls/server.crt
    key:
      file: /etc/hyperledger/fabric/tls/server.key
    rootcert:
      file: /etc/hyperledger/fabric/tls/ca.crt
    clientRootCAs:
      files:
        - /etc/hyperledger/fabric/tls/ca.crt
    clientKey:
      file:
    clientCert:
      file:
  fileSystemPath: /var/hyperledger/production
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  mspConfigPath: /etc/hyperledger/fabric/msp
  localMspId: MBBankMSP
  client:
    connTimeout: 3s
  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
    reconnectBackoffThreshold: 3600s
  localMspType: bccsp
  profile:
    enabled: false
    address: 0.0.0.0:6060
  adminService:
    enabled: false
  handlers:
    authFilters:
      -
        name: DefaultAuth
      -
        name: ExpirationCheck
    decorators:
      -
        name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
        library:
    validators:
      vscc:
        name: DefaultValidation
        library:
  validatorPoolSize:
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    orgMembersAllowedAccess: false
  limits:
    concurrency:
      qscc: 500
    totalQSize: 1000
    ifMetrics:
      enabled: false
  metrics:
    provider: disabled
    statsd:
      address: 0.0.0.0:8125
      writeInterval: 10s
      prefix: ""
  chaincode:
    id:
      path:
      name:
    builder: $(DOCKER_NS)/fabric-ccenv:$(ARCH)-$(PROJECT_VERSION)
    pull: false
    golang:
      runtime: $(BASE_DOCKER_NS)/fabric-baseos:$(ARCH)-$(PROJECT_VERSION)
      dynamicLink: false
    car:
      runtime: $(BASE_DOCKER_NS)/fabric-baseos:$(ARCH)-$(PROJECT_VERSION)
    java:
      runtime: $(DOCKER_NS)/fabric-javaenv:$(ARCH)-$(PROJECT_VERSION)
    node:
      runtime: $(BASE_DOCKER_NS)/fabric-baseos:$(ARCH)-$(PROJECT_VERSION)
    startuptimeout: 300s
    executetimeout: 30s
    mode: net
    keepalive: 0
    system:
      +lifecycle: true
      _lifecycle: true
      cscc: true
      lscc: true
      qscc: true
    systemPlugins:
    logging:
      level: info
      shim: info
      format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
  ledgersData:
    path: /var/hyperledger/production/ledgersData
  operations:
    listenAddress: 127.0.0.1:9443
    tls:
      enabled: false
      cert:
        file:
      key:
        file:
      clientAuthRequired: false
      clientRootCAs:
        files: []
  vm:
    endpoint: unix:///host/var/run/docker.sock
    docker:
      tls:
        enabled: false
        cert:
          file:
        key:
          file:
        ca:
          file:
      attachStdout: false
      hostConfig:
        NetworkMode: kindledger_fabric-net
        Dns:
          - 127.0.0.1
        LogConfig:
          Type: json-file
          Config:
            max-size: "50m"
            max-file: "5"
        Memory: 2147483648
  vmEndpoint: unix:///host/var/run/docker.sock
  vmDocker:
    tls:
      enabled: false
      cert:
        file:
      key:
        file:
      ca:
        file:
    attachStdout: false
    hostConfig:
      NetworkMode: kindledger_fabric-net
      Dns:
        - 127.0.0.1
      LogConfig:
        Type: json-file
        Config:
          max-size: "50m"
          max-file: "5"
      Memory: 2147483648
  vmDockerTLS:
    enabled: false
    cert:
      file:
    key:
      file:
    ca:
      file:
  vmDockerAttachStdout: false
  vmDockerHostConfig:
    NetworkMode: kindledger_fabric-net
    Dns:
      - 127.0.0.1
    LogConfig:
      Type: json-file
      Config:
        max-size: "50m"
        max-file: "5"
    Memory: 2147483648
